### ISSUE TITLE
Export should read Import

### ISSUE THREAD

**Issue by kjbetz** [trevor-ofarrell/PGNBuddy-V3#66]
I believe instead of using the verb Export, it should be Import games from Lichess. You're bringing games _into_ this system _from_ an external source.

Happy to possibly take on putting together PR for this.

**Comment by trevor-ofarrell** [comment]
That did cross my mind at some point aha, Thanks for pointing it out. Feel free to submit a PR :)

**Comment by trevor-ofarrell** [comment]
took care of it in this PR https://github.com/trevor-ofarrell/PGNBuddy-V3/pull/67
